[2021-11-29 12:18:50,615] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2020-01-09T00:00:00+00:00 [queued]>
[2021-11-29 12:18:50,919] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2020-01-09T00:00:00+00:00 [queued]>
[2021-11-29 12:18:50,919] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:18:50,919] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-11-29 12:18:50,920] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:18:51,138] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_4> on 2020-01-09T00:00:00+00:00
[2021-11-29 12:18:51,194] {standard_task_runner.py:52} INFO - Started process 110207 to run task
[2021-11-29 12:18:51,259] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_4', '2020-01-09T00:00:00+00:00', '--job-id', '76', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpa2sogtzp', '--error-file', '/tmp/tmpgdlpnptd']
[2021-11-29 12:18:51,347] {standard_task_runner.py:77} INFO - Job 76: Subtask task_4
[2021-11-29 12:18:52,968] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_4 2020-01-09T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:18:53,886] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_4
AIRFLOW_CTX_EXECUTION_DATE=2020-01-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-09T00:00:00+00:00
[2021-11-29 12:18:53,887] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:18:53,887] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:18:53,935] {subprocess.py:75} INFO - Output:
[2021-11-29 12:18:56,960] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:18:57,286] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_4, execution_date=20200109T000000, start_date=20211129T121850, end_date=20211129T121857
[2021-11-29 12:18:57,701] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-11-29 12:18:57,830] {local_task_job.py:151} INFO - Task exited with return code 0
