[2021-11-29 12:39:14,712] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2020-04-06T00:00:00+00:00 [queued]>
[2021-11-29 12:39:15,013] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2020-04-06T00:00:00+00:00 [queued]>
[2021-11-29 12:39:15,014] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:39:15,014] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-11-29 12:39:15,015] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:39:15,283] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_3> on 2020-04-06T00:00:00+00:00
[2021-11-29 12:39:15,376] {standard_task_runner.py:52} INFO - Started process 169242 to run task
[2021-11-29 12:39:15,290] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_3', '2020-04-06T00:00:00+00:00', '--job-id', '573', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpxtdw4y_y', '--error-file', '/tmp/tmp85nw8fog']
[2021-11-29 12:39:15,515] {standard_task_runner.py:77} INFO - Job 573: Subtask task_3
[2021-11-29 12:39:16,681] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_3 2020-04-06T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:39:17,727] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2020-04-06T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-04-06T00:00:00+00:00
[2021-11-29 12:39:17,729] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:39:17,730] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:39:17,857] {subprocess.py:75} INFO - Output:
[2021-11-29 12:39:21,037] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:39:21,565] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_3, execution_date=20200406T000000, start_date=20211129T123914, end_date=20211129T123921
[2021-11-29 12:39:23,023] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-11-29 12:39:23,053] {local_task_job.py:151} INFO - Task exited with return code 0
