[2021-11-29 12:53:40,784] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 2020-02-01T00:00:00+00:00 [queued]>
[2021-11-29 12:53:40,814] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 2020-02-01T00:00:00+00:00 [queued]>
[2021-11-29 12:53:40,814] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:53:40,815] {taskinstance.py:1068} INFO - Starting attempt 2 of 2
[2021-11-29 12:53:40,815] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:53:40,831] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_2> on 2020-02-01T00:00:00+00:00
[2021-11-29 12:53:40,834] {standard_task_runner.py:52} INFO - Started process 187472 to run task
[2021-11-29 12:53:40,855] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_2', '2020-02-01T00:00:00+00:00', '--job-id', '664', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpthh_6hfi', '--error-file', '/tmp/tmptxue26yw']
[2021-11-29 12:53:40,862] {standard_task_runner.py:77} INFO - Job 664: Subtask task_2
[2021-11-29 12:53:41,036] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_2 2020-02-01T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:53:41,194] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2020-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-01T00:00:00+00:00
[2021-11-29 12:53:41,195] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:53:41,195] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:53:41,209] {subprocess.py:75} INFO - Output:
[2021-11-29 12:53:44,235] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:53:44,312] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_2, execution_date=20200201T000000, start_date=20211129T125340, end_date=20211129T125344
[2021-11-29 12:53:44,404] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-11-29 12:53:44,413] {local_task_job.py:151} INFO - Task exited with return code 0
