[2021-11-29 12:39:35,348] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 2020-04-14T00:00:00+00:00 [queued]>
[2021-11-29 12:39:35,710] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 2020-04-14T00:00:00+00:00 [queued]>
[2021-11-29 12:39:35,710] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:39:35,711] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-11-29 12:39:35,712] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:39:36,121] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_2> on 2020-04-14T00:00:00+00:00
[2021-11-29 12:39:36,184] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_2', '2020-04-14T00:00:00+00:00', '--job-id', '590', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp_p2rnexs', '--error-file', '/tmp/tmpc6_1lmk6']
[2021-11-29 12:39:36,185] {standard_task_runner.py:77} INFO - Job 590: Subtask task_2
[2021-11-29 12:39:36,194] {standard_task_runner.py:52} INFO - Started process 170548 to run task
[2021-11-29 12:39:38,100] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_2 2020-04-14T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:39:39,789] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2020-04-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-04-14T00:00:00+00:00
[2021-11-29 12:39:39,830] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:39:39,833] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:39:40,063] {subprocess.py:75} INFO - Output:
[2021-11-29 12:39:43,252] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:39:44,018] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_2, execution_date=20200414T000000, start_date=20211129T123935, end_date=20211129T123944
[2021-11-29 12:39:46,137] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-11-29 12:39:46,405] {local_task_job.py:151} INFO - Task exited with return code 0
