[2021-11-29 12:36:12,009] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-03-10T00:00:00+00:00 [queued]>
[2021-11-29 12:36:12,267] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-03-10T00:00:00+00:00 [queued]>
[2021-11-29 12:36:12,268] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:36:12,268] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-11-29 12:36:12,269] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:36:12,440] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_1> on 2020-03-10T00:00:00+00:00
[2021-11-29 12:36:12,530] {standard_task_runner.py:52} INFO - Started process 158169 to run task
[2021-11-29 12:36:12,644] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_1', '2020-03-10T00:00:00+00:00', '--job-id', '432', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpytdryljk', '--error-file', '/tmp/tmpqdmi20_9']
[2021-11-29 12:36:12,679] {standard_task_runner.py:77} INFO - Job 432: Subtask task_1
[2021-11-29 12:36:13,784] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_1 2020-03-10T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:36:14,876] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2020-03-10T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-03-10T00:00:00+00:00
[2021-11-29 12:36:14,877] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:36:14,877] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:36:14,997] {subprocess.py:75} INFO - Output:
[2021-11-29 12:36:18,221] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:36:18,896] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_1, execution_date=20200310T000000, start_date=20211129T123612, end_date=20211129T123618
[2021-11-29 12:36:20,792] {taskinstance.py:1245} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2021-11-29 12:36:20,927] {local_task_job.py:151} INFO - Task exited with return code 0
