[2021-11-29 12:35:32,336] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2020-02-22T00:00:00+00:00 [queued]>
[2021-11-29 12:35:32,627] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2020-02-22T00:00:00+00:00 [queued]>
[2021-11-29 12:35:32,627] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:35:32,627] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-11-29 12:35:32,627] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:35:32,809] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_4> on 2020-02-22T00:00:00+00:00
[2021-11-29 12:35:32,867] {standard_task_runner.py:52} INFO - Started process 155791 to run task
[2021-11-29 12:35:32,986] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_4', '2020-02-22T00:00:00+00:00', '--job-id', '410', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp09io8b39', '--error-file', '/tmp/tmpzbhhbdpt']
[2021-11-29 12:35:33,066] {standard_task_runner.py:77} INFO - Job 410: Subtask task_4
[2021-11-29 12:35:34,064] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_4 2020-02-22T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:35:35,511] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_4
AIRFLOW_CTX_EXECUTION_DATE=2020-02-22T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-22T00:00:00+00:00
[2021-11-29 12:35:35,512] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:35:35,513] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:35:35,670] {subprocess.py:75} INFO - Output:
[2021-11-29 12:35:38,781] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:35:39,239] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_4, execution_date=20200222T000000, start_date=20211129T123532, end_date=20211129T123539
[2021-11-29 12:35:40,549] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-11-29 12:35:40,554] {local_task_job.py:151} INFO - Task exited with return code 0
