[2021-11-29 12:25:37,650] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2020-01-04T00:00:00+00:00 [queued]>
[2021-11-29 12:25:37,667] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2020-01-04T00:00:00+00:00 [queued]>
[2021-11-29 12:25:37,667] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:25:37,667] {taskinstance.py:1068} INFO - Starting attempt 2 of 2
[2021-11-29 12:25:37,668] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:25:37,677] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_4> on 2020-01-04T00:00:00+00:00
[2021-11-29 12:25:37,680] {standard_task_runner.py:52} INFO - Started process 126250 to run task
[2021-11-29 12:25:37,687] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_4', '2020-01-04T00:00:00+00:00', '--job-id', '146', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpds3rbazg', '--error-file', '/tmp/tmp0ngilieq']
[2021-11-29 12:25:37,688] {standard_task_runner.py:77} INFO - Job 146: Subtask task_4
[2021-11-29 12:25:37,766] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_4 2020-01-04T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:25:37,850] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_4
AIRFLOW_CTX_EXECUTION_DATE=2020-01-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-04T00:00:00+00:00
[2021-11-29 12:25:37,853] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:25:37,854] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:25:37,864] {subprocess.py:75} INFO - Output:
[2021-11-29 12:25:40,870] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:25:40,937] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_4, execution_date=20200104T000000, start_date=20211129T122537, end_date=20211129T122540
[2021-11-29 12:25:40,973] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-11-29 12:25:40,978] {local_task_job.py:151} INFO - Task exited with return code 0
