[2021-11-30 09:15:53,328] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 2021-11-29T00:00:00+00:00 [queued]>
[2021-11-30 09:15:53,438] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 2021-11-29T00:00:00+00:00 [queued]>
[2021-11-30 09:15:53,439] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-30 09:15:53,440] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-11-30 09:15:53,440] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-30 09:15:53,528] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_2> on 2021-11-29T00:00:00+00:00
[2021-11-30 09:15:53,531] {standard_task_runner.py:52} INFO - Started process 206068 to run task
[2021-11-30 09:15:53,550] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_2', '2021-11-29T00:00:00+00:00', '--job-id', '680', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpfmv5ajid', '--error-file', '/tmp/tmpnwcbf6uj']
[2021-11-30 09:15:53,604] {standard_task_runner.py:77} INFO - Job 680: Subtask task_2
[2021-11-30 09:15:53,962] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_2 2021-11-29T00:00:00+00:00 [running]> on host airflowvm
[2021-11-30 09:15:54,445] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2021-11-29T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-29T00:00:00+00:00
[2021-11-30 09:15:54,446] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-30 09:15:54,447] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-30 09:15:54,511] {subprocess.py:75} INFO - Output:
[2021-11-30 09:15:57,553] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-30 09:15:57,718] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_2, execution_date=20211129T000000, start_date=20211130T091553, end_date=20211130T091557
[2021-11-30 09:15:57,937] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-11-30 09:15:57,959] {local_task_job.py:151} INFO - Task exited with return code 0
