[2021-11-29 12:19:00,928] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2020-01-10T00:00:00+00:00 [queued]>
[2021-11-29 12:19:01,147] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2020-01-10T00:00:00+00:00 [queued]>
[2021-11-29 12:19:01,148] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:19:01,148] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-11-29 12:19:01,176] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:19:01,285] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_4> on 2020-01-10T00:00:00+00:00
[2021-11-29 12:19:01,293] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_4', '2020-01-10T00:00:00+00:00', '--job-id', '81', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp9lvdp7pv', '--error-file', '/tmp/tmpww33a1tc']
[2021-11-29 12:19:01,357] {standard_task_runner.py:52} INFO - Started process 111124 to run task
[2021-11-29 12:19:01,493] {standard_task_runner.py:77} INFO - Job 81: Subtask task_4
[2021-11-29 12:19:02,166] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_4 2020-01-10T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:19:03,100] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_4
AIRFLOW_CTX_EXECUTION_DATE=2020-01-10T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-10T00:00:00+00:00
[2021-11-29 12:19:03,101] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:19:03,102] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:19:03,172] {subprocess.py:75} INFO - Output:
[2021-11-29 12:19:06,245] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:19:06,881] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_4, execution_date=20200110T000000, start_date=20211129T121900, end_date=20211129T121906
[2021-11-29 12:19:08,755] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-11-29 12:19:08,779] {local_task_job.py:151} INFO - Task exited with return code 0
