[2021-11-29 12:36:29,998] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-03-14T00:00:00+00:00 [queued]>
[2021-11-29 12:36:30,273] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-03-14T00:00:00+00:00 [queued]>
[2021-11-29 12:36:30,274] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:36:30,274] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-11-29 12:36:30,275] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:36:30,412] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_1> on 2020-03-14T00:00:00+00:00
[2021-11-29 12:36:30,566] {standard_task_runner.py:52} INFO - Started process 159236 to run task
[2021-11-29 12:36:30,588] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_1', '2020-03-14T00:00:00+00:00', '--job-id', '448', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp7xsed9fx', '--error-file', '/tmp/tmp9ve6kkqp']
[2021-11-29 12:36:30,676] {standard_task_runner.py:77} INFO - Job 448: Subtask task_1
[2021-11-29 12:36:32,066] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_1 2020-03-14T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:36:33,367] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2020-03-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-03-14T00:00:00+00:00
[2021-11-29 12:36:33,368] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:36:33,368] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:36:33,564] {subprocess.py:75} INFO - Output:
[2021-11-29 12:36:36,731] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:36:37,898] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_1, execution_date=20200314T000000, start_date=20211129T123629, end_date=20211129T123637
[2021-11-29 12:36:38,785] {taskinstance.py:1245} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2021-11-29 12:36:39,069] {local_task_job.py:151} INFO - Task exited with return code 0
