[2021-11-29 12:53:36,573] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-02-01T00:00:00+00:00 [queued]>
[2021-11-29 12:53:36,589] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-02-01T00:00:00+00:00 [queued]>
[2021-11-29 12:53:36,590] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:53:36,590] {taskinstance.py:1068} INFO - Starting attempt 2 of 2
[2021-11-29 12:53:36,591] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:53:36,601] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_1> on 2020-02-01T00:00:00+00:00
[2021-11-29 12:53:36,604] {standard_task_runner.py:52} INFO - Started process 187300 to run task
[2021-11-29 12:53:36,611] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_1', '2020-02-01T00:00:00+00:00', '--job-id', '663', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp8wngd522', '--error-file', '/tmp/tmp3uozp_8x']
[2021-11-29 12:53:36,613] {standard_task_runner.py:77} INFO - Job 663: Subtask task_1
[2021-11-29 12:53:36,692] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_1 2020-02-01T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:53:36,786] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2020-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-01T00:00:00+00:00
[2021-11-29 12:53:36,787] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:53:36,788] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:53:36,795] {subprocess.py:75} INFO - Output:
[2021-11-29 12:53:39,800] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:53:39,836] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_1, execution_date=20200201T000000, start_date=20211129T125336, end_date=20211129T125339
[2021-11-29 12:53:39,874] {taskinstance.py:1245} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2021-11-29 12:53:39,916] {local_task_job.py:151} INFO - Task exited with return code 0
