[2021-11-29 12:30:02,980] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2020-01-26T00:00:00+00:00 [queued]>
[2021-11-29 12:30:03,626] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2020-01-26T00:00:00+00:00 [queued]>
[2021-11-29 12:30:03,626] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:30:03,626] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-11-29 12:30:03,626] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:30:03,935] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_4> on 2020-01-26T00:00:00+00:00
[2021-11-29 12:30:04,429] {standard_task_runner.py:52} INFO - Started process 137218 to run task
[2021-11-29 12:30:05,028] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_4', '2020-01-26T00:00:00+00:00', '--job-id', '205', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpmiwc3z4c', '--error-file', '/tmp/tmpy82el5am']
[2021-11-29 12:30:05,260] {standard_task_runner.py:77} INFO - Job 205: Subtask task_4
[2021-11-29 12:30:08,935] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_4 2020-01-26T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:30:10,883] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_4
AIRFLOW_CTX_EXECUTION_DATE=2020-01-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-26T00:00:00+00:00
[2021-11-29 12:30:10,897] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:30:10,897] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:30:11,299] {subprocess.py:75} INFO - Output:
[2021-11-29 12:30:14,487] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:30:15,139] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_4, execution_date=20200126T000000, start_date=20211129T123003, end_date=20211129T123015
[2021-11-29 12:30:15,804] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-11-29 12:30:15,822] {local_task_job.py:151} INFO - Task exited with return code 0
