[2021-11-29 12:52:54,045] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2020-01-26T00:00:00+00:00 [queued]>
[2021-11-29 12:52:54,206] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2020-01-26T00:00:00+00:00 [queued]>
[2021-11-29 12:52:54,207] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:52:54,212] {taskinstance.py:1068} INFO - Starting attempt 2 of 2
[2021-11-29 12:52:54,223] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:52:54,327] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_4> on 2020-01-26T00:00:00+00:00
[2021-11-29 12:52:54,333] {standard_task_runner.py:52} INFO - Started process 185671 to run task
[2021-11-29 12:52:54,344] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_4', '2020-01-26T00:00:00+00:00', '--job-id', '656', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp24_3x11c', '--error-file', '/tmp/tmp4bllmxw5']
[2021-11-29 12:52:54,435] {standard_task_runner.py:77} INFO - Job 656: Subtask task_4
[2021-11-29 12:52:54,977] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_4 2020-01-26T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:52:55,621] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_4
AIRFLOW_CTX_EXECUTION_DATE=2020-01-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-26T00:00:00+00:00
[2021-11-29 12:52:55,622] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:52:55,623] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:52:55,681] {subprocess.py:75} INFO - Output:
[2021-11-29 12:52:58,784] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:52:58,965] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_4, execution_date=20200126T000000, start_date=20211129T125254, end_date=20211129T125258
[2021-11-29 12:52:59,253] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-11-29 12:52:59,271] {local_task_job.py:151} INFO - Task exited with return code 0
