[2021-11-29 12:30:01,250] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2020-01-19T00:00:00+00:00 [queued]>
[2021-11-29 12:30:01,791] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2020-01-19T00:00:00+00:00 [queued]>
[2021-11-29 12:30:01,791] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:30:01,791] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-11-29 12:30:01,791] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:30:02,127] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_4> on 2020-01-19T00:00:00+00:00
[2021-11-29 12:30:02,210] {standard_task_runner.py:52} INFO - Started process 137150 to run task
[2021-11-29 12:30:02,291] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_4', '2020-01-19T00:00:00+00:00', '--job-id', '195', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp7pd8_1vn', '--error-file', '/tmp/tmp1dlrivx8']
[2021-11-29 12:30:02,490] {standard_task_runner.py:77} INFO - Job 195: Subtask task_4
[2021-11-29 12:30:06,256] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_4 2020-01-19T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:30:08,716] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_4
AIRFLOW_CTX_EXECUTION_DATE=2020-01-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-19T00:00:00+00:00
[2021-11-29 12:30:08,745] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:30:08,847] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:30:09,248] {subprocess.py:75} INFO - Output:
[2021-11-29 12:30:12,469] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:30:12,705] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_4, execution_date=20200119T000000, start_date=20211129T123001, end_date=20211129T123012
[2021-11-29 12:30:13,059] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-11-29 12:30:13,084] {local_task_job.py:151} INFO - Task exited with return code 0
