[2021-11-29 12:18:01,805] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2020-01-05T00:00:00+00:00 [queued]>
[2021-11-29 12:18:02,091] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2020-01-05T00:00:00+00:00 [queued]>
[2021-11-29 12:18:02,091] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:18:02,092] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-11-29 12:18:02,092] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:18:02,231] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_3> on 2020-01-05T00:00:00+00:00
[2021-11-29 12:18:02,294] {standard_task_runner.py:52} INFO - Started process 107317 to run task
[2021-11-29 12:18:02,239] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_3', '2020-01-05T00:00:00+00:00', '--job-id', '41', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpp7ybppbp', '--error-file', '/tmp/tmpxbmfva1_']
[2021-11-29 12:18:02,501] {standard_task_runner.py:77} INFO - Job 41: Subtask task_3
[2021-11-29 12:18:03,605] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_3 2020-01-05T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:18:04,897] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2020-01-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-05T00:00:00+00:00
[2021-11-29 12:18:04,897] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:18:04,898] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:18:05,101] {subprocess.py:75} INFO - Output:
[2021-11-29 12:18:08,382] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:18:08,894] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_3, execution_date=20200105T000000, start_date=20211129T121801, end_date=20211129T121808
[2021-11-29 12:18:09,602] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-11-29 12:18:09,734] {local_task_job.py:151} INFO - Task exited with return code 0
