[2021-11-29 12:31:23,076] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2020-02-08T00:00:00+00:00 [queued]>
[2021-11-29 12:31:23,577] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2020-02-08T00:00:00+00:00 [queued]>
[2021-11-29 12:31:23,578] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:31:23,578] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-11-29 12:31:23,579] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:31:24,049] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_3> on 2020-02-08T00:00:00+00:00
[2021-11-29 12:31:24,346] {standard_task_runner.py:52} INFO - Started process 141414 to run task
[2021-11-29 12:31:24,174] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_3', '2020-02-08T00:00:00+00:00', '--job-id', '245', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpvj4d4f4_', '--error-file', '/tmp/tmprd7fba65']
[2021-11-29 12:31:24,704] {standard_task_runner.py:77} INFO - Job 245: Subtask task_3
[2021-11-29 12:31:26,783] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_3 2020-02-08T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:31:28,324] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2020-02-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-08T00:00:00+00:00
[2021-11-29 12:31:28,325] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:31:28,325] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:31:28,563] {subprocess.py:75} INFO - Output:
[2021-11-29 12:31:31,597] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:31:32,165] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_3, execution_date=20200208T000000, start_date=20211129T123123, end_date=20211129T123132
[2021-11-29 12:31:32,820] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-11-29 12:31:32,861] {local_task_job.py:151} INFO - Task exited with return code 0
