[2021-11-29 12:26:42,811] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 2020-01-18T00:00:00+00:00 [queued]>
[2021-11-29 12:26:42,830] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 2020-01-18T00:00:00+00:00 [queued]>
[2021-11-29 12:26:42,831] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:26:42,831] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-11-29 12:26:42,832] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:26:42,844] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_2> on 2020-01-18T00:00:00+00:00
[2021-11-29 12:26:42,849] {standard_task_runner.py:52} INFO - Started process 129016 to run task
[2021-11-29 12:26:42,856] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_2', '2020-01-18T00:00:00+00:00', '--job-id', '159', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp92dzdrdk', '--error-file', '/tmp/tmph8yx8r0r']
[2021-11-29 12:26:42,858] {standard_task_runner.py:77} INFO - Job 159: Subtask task_2
[2021-11-29 12:26:42,947] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_2 2020-01-18T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:26:43,048] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2020-01-18T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-18T00:00:00+00:00
[2021-11-29 12:26:43,049] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:26:43,050] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:26:43,058] {subprocess.py:75} INFO - Output:
[2021-11-29 12:26:46,063] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:26:46,106] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_2, execution_date=20200118T000000, start_date=20211129T122642, end_date=20211129T122646
[2021-11-29 12:26:46,148] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-11-29 12:26:46,154] {local_task_job.py:151} INFO - Task exited with return code 0
