[2021-11-29 12:39:03,056] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-04-07T00:00:00+00:00 [queued]>
[2021-11-29 12:39:03,230] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-04-07T00:00:00+00:00 [queued]>
[2021-11-29 12:39:03,230] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:39:03,231] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-11-29 12:39:03,264] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:39:03,334] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_1> on 2020-04-07T00:00:00+00:00
[2021-11-29 12:39:03,389] {standard_task_runner.py:52} INFO - Started process 168677 to run task
[2021-11-29 12:39:03,419] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_1', '2020-04-07T00:00:00+00:00', '--job-id', '562', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpr8a3qxiy', '--error-file', '/tmp/tmp4_54wb41']
[2021-11-29 12:39:03,453] {standard_task_runner.py:77} INFO - Job 562: Subtask task_1
[2021-11-29 12:39:03,969] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_1 2020-04-07T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:39:04,437] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2020-04-07T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-04-07T00:00:00+00:00
[2021-11-29 12:39:04,438] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:39:04,439] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:39:04,491] {subprocess.py:75} INFO - Output:
[2021-11-29 12:39:07,641] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:39:07,906] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_1, execution_date=20200407T000000, start_date=20211129T123903, end_date=20211129T123907
[2021-11-29 12:39:08,135] {taskinstance.py:1245} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2021-11-29 12:39:08,163] {local_task_job.py:151} INFO - Task exited with return code 0
