[2021-11-29 12:33:14,214] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 2020-01-16T00:00:00+00:00 [queued]>
[2021-11-29 12:33:14,412] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 2020-01-16T00:00:00+00:00 [queued]>
[2021-11-29 12:33:14,414] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:33:14,415] {taskinstance.py:1068} INFO - Starting attempt 3 of 3
[2021-11-29 12:33:14,421] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:33:14,510] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_2> on 2020-01-16T00:00:00+00:00
[2021-11-29 12:33:14,544] {standard_task_runner.py:52} INFO - Started process 147317 to run task
[2021-11-29 12:33:14,617] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_2', '2020-01-16T00:00:00+00:00', '--job-id', '311', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpqwd72yiv', '--error-file', '/tmp/tmpnfy08jr9']
[2021-11-29 12:33:14,655] {standard_task_runner.py:77} INFO - Job 311: Subtask task_2
[2021-11-29 12:33:15,601] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_2 2020-01-16T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:33:16,353] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2020-01-16T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-16T00:00:00+00:00
[2021-11-29 12:33:16,359] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:33:16,375] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:33:16,448] {subprocess.py:75} INFO - Output:
[2021-11-29 12:33:19,538] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:33:19,872] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_2, execution_date=20200116T000000, start_date=20211129T123314, end_date=20211129T123319
[2021-11-29 12:33:20,241] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-11-29 12:33:20,261] {local_task_job.py:151} INFO - Task exited with return code 0
